baseurl = "/"
languageCode = "de-ch"
languageLang = "de"
title = "Aus dem Bauch heraus"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

# googleAnalytics id below is not used because. Instead stuff is "hardcoded" in head.html
# googleAnalytics = "G-GXV6W79DKP"
summaryLength = 20