backend:
  name: git-gateway

locale: "de"

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Artikel" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Entwurf", name: "draft", widget: "boolean", default: true }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Bild", name: "image", widget: "image", required: false }
      - { label: "Inhalt", name: "body", widget: "markdown" }
      - label: "Aufstellung"
        name: "players"
        widget: "object"
        required: false
        fields: 
        - { label: "Goalie", name: "goalie", widget: "string" }
        - { label: "Verteidiger 1", name: "v1", widget: "string" }
        - { label: "Verteidiger 2", name: "v2", widget: "string" }
        - { label: "Verteidiger 3", name: "v3", widget: "string" }
        - { label: "Verteidiger 4", name: "v4", widget: "string" }
        - { label: "Mittelfeld 1", name: "m1", widget: "string" }
        - { label: "Mittelfeld 2", name: "m2", widget: "string" }
        - { label: "Mittelfeld 3", name: "m3", widget: "string" }
        - { label: "Stürmer 1", name: "s1", widget: "string" }
        - { label: "Stürmer 2", name: "s2", widget: "string" }
        - { label: "Stürmer 3", name: "s3", widget: "string" }
        - label: "Ersatz"
          name: "ersatz"
          widget: "string"
          required: false
  - name: "pages"
    label: "Seiten"
    files:
      - file: "site/content/_index.md"
        label: "Startseite"
        name: "home"
        fields:
          - { label: Titel, name: title, widget: string }
          - {
              label: Untertitel,
              name: subtitle,
              widget: string,
              required: false,
            }
          - { label: Bild, name: image, widget: image }
      - file: "site/content/rangliste/_index.md"
        label: "Rangliste"
        name: "rangliste"
        fields:
          - { label: Titel, name: title, widget: string }
          - { label: "Datum", name: "date", widget: "datetime" }
          - { label: "Bild", name: "image", widget: "image", required: false }
